# Generated by Django 2.2 on 2020-11-08 10:58

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HWB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
    ]
